repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-ast
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-illegal-windows-names
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-toml
    - id: check-vcs-permalinks
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: forbid-submodules
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: insert-license
      name: Add license for all Python files
      files: ^src/(.*\.py$|.*\.pyi)$
      args:
        - --comment-style
        - "|#|"
        - --license-filepath
        - share/apache-2.0_header.txt
        - --fuzzy-match-generates-todo
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  -   id: shellcheck
- repo: https://github.com/woodruffw/zizmor-pre-commit
  rev: v1.11.0
  hooks:
    - id: zizmor
      args: [ --min-severity, low ]
- repo: local
  hooks:
    - id: ruff
      name: Ruff Linter
      entry: uv run ruff check --fix
      language: system
      types: [python]

    - id: ruff-format
      name: Ruff Formatter
      entry: uv run ruff format --force-exclude
      language: system
      types: [python]

    - id: pyright
      name: Pyright Type Check
      entry: uv run pyright
      language: system
      require_serial: true
      types: [python]
