name: post-oidc-jwt-to-atr
on: workflow_dispatch
permissions: { contents: read }

jobs:
  send:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Request OIDC token
        id: mint
        shell: bash
        run: |
          set -euo pipefail
          _url="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=atr-test"
          _token="${ACTIONS_ID_TOKEN_REQUEST_TOKEN}"
          _jwt="$(curl -sS -H "Authorization: bearer ${_token}" "${_url}" | jq -er '.value')"
          echo "::add-mask::${_jwt}"
          echo "jwt=${_jwt}" >> "$GITHUB_OUTPUT"

      - name: Generate an ephemeral SSH key
        id: ssh
        shell: bash
        run: |
          set -euo pipefail
          ssh-keygen -t ed25519 -N "" -f "$RUNNER_TEMP/ssh_key"
          echo "SSH_PRIVATE_KEY_PATH=$RUNNER_TEMP/ssh_key" >> "$GITHUB_ENV"
          echo "SSH_PUBLIC_KEY=$(cat "$RUNNER_TEMP/ssh_key.pub")" >> "$GITHUB_ENV"

      - name: POST to ATR
        shell: bash
        run: |
          set -euo pipefail
          curl -sS -X POST \
            -H "Content-Type: application/json" \
            -d "{\"jwt\":\"${{ steps.mint.outputs.jwt }}\",\"ssh_key\":\"$SSH_PUBLIC_KEY\"}" \
            https://release-test.apache.org/api/jwt/github
